version: "3"
services:
    rclone:
        image: rclone/rclone:1.50
        entrypoint: ["sh","/init_rclone"]
        container_name: rclone
        labels:
            - traefik.enable=false
        env_file: .env
        cap_add:
          - MKNOD
          - SYS_ADMIN
        restart: always
        security_opt:
          - apparmor:unconfined
        devices:
          - /dev/fuse
        tty: true
        ulimits:
          nproc: 65535
          nofile:
              soft: 49999
              hard: 99999
        volumes:
                - ${LOCAL_SYNC_FOLDER}:/opt/sync_folder
                - ./auth/key.json:/auth/key.json:ro
                - ./rclone/init_rclone:/init_rclone:ro
                - ./rclone/scripts:/scripts:ro
                - /etc/localtime:/etc/localtime:ro
